# HTTP — редирект на HTTPS
server {
    listen 80;
    server_name витрина-рент.рф xn----7sbfoma9adveqi.xn--p1ai aodiapazon.ru www.aodiapazon.ru;
    client_max_body_size 50M;
    return 301 https://$host$request_uri;
}

# HTTPS — витрина-рент.рф
server {
    listen 443 ssl;
    server_name витрина-рент.рф xn----7sbfoma9adveqi.xn--p1ai;
    client_max_body_size 50M;
    ssl_certificate         /etc/letsencrypt/live/xn----7sbfoma9adveqi.xn--p1ai/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/xn----7sbfoma9adveqi.xn--p1ai/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        client_max_body_size 50M;
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# HTTPS — aodiapazon.ru
server {
    listen 443 ssl;
    server_name aodiapazon.ru www.aodiapazon.ru;
    client_max_body_size 50M;
    ssl_certificate         /etc/letsencrypt/live/aodiapazon.ru/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/aodiapazon.ru/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location / {
        client_max_body_size 50M;
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
